version: 1-alpha.1

releases:
  vega-sp-testing:
    name: VEGA Settlement Platform
    autodeploy-on: default
    chart: csssr/static-site@~1.0.0
    static-params:
      projectID: vega-sp
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
    builds:
      - workflow: build-static.yaml
        values:
          buildID: build-{{ .Build.RunID }}
