name: Проверка покрытия
on:
  pull_request:
    types: [unlabeled, opened, synchronize, reopened, ready_for_review]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: yarn generate:types
        env:
          VEGA_SCHEMA_PATH: graphql.schema.json

      - run: yarn coverage
        if: always()

      - uses: Inzephirum/gha-test-coverage-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_threshold: '100'
          report_file_path: './coverage/lcov.info'
