name: Сборка и деплой VEGA-SP
on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: vega-sp

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./vega-sp

      - run: yarn build
        working-directory: ./vega-sp

      - uses: ./actions/deploy-static-site/v1beta1
        with:
          project-id: vega-sp
          files: ./vega-sp/dist
          auth: ${{ secrets.CSSSR_AUTH }}
          token: ${{ secrets.GITHUB_TOKEN }}
